#ifndef LOAN_GUARD__H
#define LOAN_GUARD__H

#include <stdio.h>
#include "common.h"
#include "type_return_code.h"

typedef struct _Loan {
    char* username;
    unsigned int* id;
    struct _Loan* next;
} Loan;

typedef struct _Id {
    unsigned int id;
    unsigned int* next;
} Id;

typedef struct _IdList {
    unsigned int list[LIST_LEN];
    int length;
} IdList;

//saves the database of loans in the specified file
//returns 0 if loans were stored correctly, or an error code otherwise
int store_loans(FILE *file);

//loads the database of loans from the specified file
//the file must have been generated by a previous call to store_loans()
//returns 0 if loans were loaded correctly, or an error code otherwise
int load_loans(FILE *file);

// gets all the loans of the user
IdList get_loans(const char* username);

// add loan to a user by username
int add_loans(char* username, unsigned int id);

// free any resource allocated for the loans
void clean_loans(Loan* loanHeadNode);

#endif
