#ifndef USER_GUARD__H
#define USER_GUARD__H

#include <stdio.h>
#include "type_return_code.h"

typedef struct _User {
    char* username;
    char* password;
    struct _User* next;
} User;

//saves the database of users in the specified file
//returns 0 if users were stored correctly, or an error code otherwise
int store_users(FILE *file);

//loads the database of users from the specified file
//the file must have been generated by a previous call to store_users()
//returns 0 if users were loaded correctly, or an error code otherwise
int load_users(FILE *file);

// borrow a book from the library
// return 0 if borrow the book successfully, or an error code otherwise
int borrow_book(User user, int id);

// return a book to the library
// return 0 if return the book successfully, or an error code otherwise
int return_book(User user, int id);

#endif
